apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: myapp
  name: deployment-example
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 1
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: nginx-app
          image: nginx:1.25.3
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "150m"
              memory: "256Mi"
